spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apargo_wa_messaging?useSSL=false&serverTimezone=UTC
    username: root
    password: yuvraj@3933

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.aigreentick.services.wabaaccounts: DEBUG